# Conexión dinámica para Render
spring.datasource.url=jdbc:postgresql://petramas_bd_user:gs0kRSXToVNVVspt6jTNBgRiZN08RgbT@dpg-daee27qd0e5s738519vg-a.oregon-postgres.render.com:5432/petramas_bd
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Evitar errores de conexión inactiva en la nube
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000